#!/usr/bin/env python


#### Add impl to PYTHONPATH

import os, sys

def parentOf(path, n=1):
    return '/'.join(path.rstrip('/').split('/')[:-n])

REPO = parentOf(os.path.abspath(__file__), n=2)

sys.path.append('%s/impl' % REPO)


#### Main

if __name__ == '__main__':
    from spriteutils import main, spriteHtmlViz
    main(spriteHtmlViz)
